nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:\d+$', '^http://127\.0\.0\.1:\d+$']
        allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
        allow_headers: ['Content-Type','Accept']
        allow_credentials: true
        max_age: 3600
    paths: { '^/': ~ }
