<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260918101725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fournisseur (id UUID NOT NULL, code VARCHAR(20) DEFAULT NULL, raison_sociale VARCHAR(255) NOT NULL, sigle VARCHAR(50) NOT NULL, tel VARCHAR(50) DEFAULT NULL, mobile VARCHAR(50) DEFAULT NULL, personne_ressource VARCHAR(255) DEFAULT NULL, contact_personne VARCHAR(50) DEFAULT NULL, adresse TEXT DEFAULT NULL, bp VARCHAR(255) DEFAULT NULL, agree BOOLEAN DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, rccim VARCHAR(50) DEFAULT NULL, cc VARCHAR(50) DEFAULT NULL, note INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
